# -*- coding: utf-8 -*-
"""temperature_analysisdataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IjwlUTqgQjoo34TfGK3Rap6l0wTC-x3
"""

!pip install dash plotly scikit-learn pandas statsmodels dash-bootstrap-components

#IMPORTS
import pandas as pd
import numpy as np
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import dash_bootstrap_components as dbc
import plotly.graph_objs as go
from sklearn.svm import OneClassSVM
from statsmodels.tsa.arima.model import ARIMA
import warnings

warnings.filterwarnings('ignore')

# Data loader and preparation
max_temp = pd.read_csv('/content/TEMP_ANNUAL_MAX_1901-2021.csv')
min_temp = pd.read_csv('/content/TEMP_ANNUAL_MIN_1901-2021.csv')
mean_temp = pd.read_csv('/content/TEMP_ANNUAL_MEAN_1901-2021.csv')

seasons = ['JAN-FEB', 'MAR-MAY', 'JUN-SEP', 'OCT-DEC']

for column in seasons:
    max_temp[column] = pd.to_numeric(max_temp[column], errors='coerce')
    min_temp[column] = pd.to_numeric(min_temp[column], errors='coerce')
    mean_temp[column] = pd.to_numeric(mean_temp[column], errors='coerce')

combined_data = pd.DataFrame({
    'Year': mean_temp['YEAR'],
    'Max_JAN-FEB': max_temp['JAN-FEB'], 'Max_MAR-MAY': max_temp['MAR-MAY'],
    'Max_JUN-SEP': max_temp['JUN-SEP'], 'Max_OCT-DEC': max_temp['OCT-DEC'],
    'Min_JAN-FEB': min_temp['JAN-FEB'], 'Min_MAR-MAY': min_temp['MAR-MAY'],
    'Min_JUN-SEP': min_temp['JUN-SEP'], 'Min_OCT-DEC': min_temp['OCT-DEC'],
    'Mean_JAN-FEB': mean_temp['JAN-FEB'], 'Mean_MAR-MAY': mean_temp['MAR-MAY'],
    'Mean_JUN-SEP': mean_temp['JUN-SEP'], 'Mean_OCT-DEC': mean_temp['OCT-DEC']
})

# Dash APP
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.FLATLY])

app.layout = dbc.Container([
    dbc.Row([
        dbc.Col(html.H2("Glimpse into climate fluctuations of India (1901-2021)",
                        className="text-center text-primary mt-4 mb-4 fw-bold"), width=12)
    ]),

    dbc.Card([
        dbc.CardBody([
            dbc.Tabs([
                dbc.Tab(label='☀️❄️ Seasonal Trends 🌸🍂', children=[
                    html.Br(),
                    html.Label("Select Season:", className="fw-bold"),
                    dcc.Dropdown(id='season-trend', options=[{'label': s, 'value': s} for s in seasons], value='JAN-FEB', clearable=False, className="mb-3"),
                    dcc.Graph(id='seasonal-trends')
                ]),

                dbc.Tab(label='Data Distribution', children=[
                    html.Br(),
                    html.Label("Select Season:", className="fw-bold"),
                    dcc.Dropdown(id='season-box', options=[{'label': s, 'value': s} for s in seasons], value='JAN-FEB', clearable=False, className="mb-3"),
                    dcc.Graph(id='seasonal-box-plot')
                ]),

                dbc.Tab(label='🚨 Extreme Events', children=[
                    html.Br(),
                    html.Label("Select Season:", className="fw-bold"),
                    dcc.Dropdown(id='season-extreme', options=[{'label': s, 'value': s} for s in seasons], value='JAN-FEB', clearable=False, className="mb-3"),
                    dcc.Graph(id='seasonal-extreme-events')
                ]),

                dbc.Tab(label='🧩 Correlation Map', children=[
                    html.Br(),
                    html.Label("Select Season:", className="fw-bold"),
                    dcc.Dropdown(id='season-correlation', options=[{'label': s, 'value': s} for s in seasons], value='JAN-FEB', clearable=False, className="mb-3"),
                    dcc.Graph(id='seasonal-correlation-heatmap')
                ]),

                dbc.Tab(label='👾 Anomaly Detection', children=[
                    html.Br(),
                    dbc.Row([
                        dbc.Col([
                            html.Label("Select Season:", className="fw-bold"),
                            dcc.Dropdown(id='svm-season', options=[{'label': s, 'value': s} for s in seasons], value='JAN-FEB', clearable=False)
                        ], width=6),
                        dbc.Col([
                            html.Label("Select Temperature Type:", className="fw-bold"),
                            dcc.Dropdown(id='svm-temp-type', options=[
                                {'label': 'Max Temperature', 'value': 'Max'},
                                {'label': 'Min Temperature', 'value': 'Min'},
                                {'label': 'Mean Temperature', 'value': 'Mean'}
                            ], value='Mean', clearable=False)
                        ], width=6)
                    ], className="mb-3"),
                    dcc.Graph(id='svm-anomaly-plot')
                ]),

                dbc.Tab(label='🔮 Forecasts with ARIMA', children=[
                    html.Br(),
                    html.Label("Select Season:", className="fw-bold"),
                    dcc.Dropdown(id='arima-season', options=[{'label': s, 'value': s} for s in seasons], value='JAN-FEB', clearable=False, className="mb-3"),
                    dcc.Graph(id='arima-forecast-plot')
                ])
            ], className="nav-fill")
        ])
    ], className="shadow-sm mb-4")
], fluid=True, style={'maxWidth': '1200px'})

# CALLBACKS
layout_template = 'plotly_white'

@app.callback(Output('seasonal-trends', 'figure'), [Input('season-trend', 'value')])
def update_seasonal_trends(season):
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=combined_data['Year'], y=combined_data[f'Max_{season}'], mode='lines', name='Max Temp', line=dict(color='#e74c3c', width=2)))
    fig.add_trace(go.Scatter(x=combined_data['Year'], y=combined_data[f'Mean_{season}'], mode='lines', name='Mean Temp', line=dict(color='#2ecc71', width=2)))
    fig.add_trace(go.Scatter(x=combined_data['Year'], y=combined_data[f'Min_{season}'], mode='lines', name='Min Temp', line=dict(color='#3498db', width=2)))
    fig.update_layout(title=f'Historical Temperature Trends ({season})', xaxis_title='Year', yaxis_title='Temperature (°C)', template=layout_template, hovermode="x unified")
    return fig

@app.callback(Output('seasonal-box-plot', 'figure'), [Input('season-box', 'value')])
def update_seasonal_box_plot(season):
    fig = go.Figure()
    fig.add_trace(go.Box(y=combined_data[f'Mean_{season}'], name=f'{season} Mean', marker_color='#9b59b6', boxpoints='all', jitter=0.3, pointpos=-1.8))
    fig.update_layout(title=f'Temperature Distribution & Outliers ({season})', yaxis_title='Temperature (°C)', template=layout_template)
    return fig

@app.callback(Output('seasonal-extreme-events', 'figure'), [Input('season-extreme', 'value')])
def update_seasonal_extreme_events(season):
    threshold_max = combined_data[f'Max_{season}'].mean() + combined_data[f'Max_{season}'].std()
    threshold_min = combined_data[f'Min_{season}'].mean() - combined_data[f'Min_{season}'].std()

    extreme_max = combined_data[combined_data[f'Max_{season}'] > threshold_max]
    extreme_min = combined_data[combined_data[f'Min_{season}'] < threshold_min]

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=combined_data['Year'], y=combined_data[f'Max_{season}'], mode='lines', name='Max Temp Trend', line=dict(color='#e74c3c'), opacity=0.3))
    fig.add_trace(go.Scatter(x=combined_data['Year'], y=combined_data[f'Min_{season}'], mode='lines', name='Min Temp Trend', line=dict(color='#3498db'), opacity=0.3))
    if not extreme_max.empty:
        fig.add_trace(go.Scatter(x=extreme_max['Year'], y=extreme_max[f'Max_{season}'], mode='markers', name='Extreme Highs (+1 SD)', marker=dict(color='red', size=8, line=dict(width=1, color='DarkSlateGrey'))))
    if not extreme_min.empty:
        fig.add_trace(go.Scatter(x=extreme_min['Year'], y=extreme_min[f'Min_{season}'], mode='markers', name='Extreme Lows (-1 SD)', marker=dict(color='blue', size=8, line=dict(width=1, color='DarkSlateGrey'))))

    fig.update_layout(title=f'Statistical Extreme Events ({season})', xaxis_title='Year', yaxis_title='Temperature (°C)', template=layout_template, hovermode="x unified")
    return fig

@app.callback(Output('seasonal-correlation-heatmap', 'figure'), [Input('season-correlation', 'value')])
def render_seasonal_correlation_heatmap(season):
    filtered_data = combined_data[[f'Max_{season}', f'Mean_{season}', f'Min_{season}']]
    filtered_data.columns = ['Max Temp', 'Mean Temp', 'Min Temp']
    correlation_matrix = filtered_data.corr()

    fig = go.Figure(data=go.Heatmap(
        z=correlation_matrix.values, x=correlation_matrix.columns, y=correlation_matrix.index,
        colorscale='Tealrose', text=np.round(correlation_matrix.values, 2), texttemplate="%{text}"
    ))
    fig.update_layout(title=f'Temperature Correlation Matrix ({season})', template=layout_template)
    return fig

@app.callback(Output('svm-anomaly-plot', 'figure'), [Input('svm-season', 'value'), Input('svm-temp-type', 'value')])
def update_svm_anomalies(season, temp_type):
    col_name = f'{temp_type}_{season}'
    df_temp = combined_data[['Year', col_name]].copy()
    df_temp[col_name] = df_temp[col_name].fillna(df_temp[col_name].mean())

    clf = OneClassSVM(nu=0.05, kernel='rbf', gamma=0.1)
    df_temp['Anomaly'] = clf.fit_predict(df_temp[[col_name]])
    anomalies = df_temp[df_temp['Anomaly'] == -1]
    normal = df_temp[df_temp['Anomaly'] == 1]

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=df_temp['Year'], y=df_temp[col_name], mode='lines', name='Overall Trend', line=dict(color='lightgray', width=2)))
    fig.add_trace(go.Scatter(x=normal['Year'], y=normal[col_name], mode='markers', name='Normal Years', marker=dict(color='#2c3e50', size=6)))
    fig.add_trace(go.Scatter(x=anomalies['Year'], y=anomalies[col_name], mode='markers', name='Anomalous Years', marker=dict(color='#e74c3c', size=10, symbol='x', line=dict(width=1, color='DarkSlateGrey'))))

    # Base layout
    layout_updates = dict(
        title=f'Machine Learning Anomaly Detection (SVM): {temp_type} Temp ({season})',
        xaxis_title='Year',
        yaxis_title='Temperature (°C)',
        template=layout_template,
        hovermode="x unified"
    )

    # auto scale min-max to capture space accordingly
    if temp_type == 'Mean':
        all_mean_cols = [f'Mean_{s}' for s in seasons]
        global_min = combined_data[all_mean_cols].min().min()
        global_max = combined_data[all_mean_cols].max().max()
        layout_updates['yaxis'] = dict(range=[global_min - 0.5, global_max + 0.5])

    fig.update_layout(**layout_updates)
    return fig

@app.callback(Output('arima-forecast-plot', 'figure'), [Input('arima-season', 'value')])
def update_arima_forecast(season):
    y = combined_data[f'Mean_{season}'].dropna().values
    years = combined_data['Year'].dropna().values

    # NEW FIX: Added 'trend="t"' to force ARIMA to project the long-term trend
    model = ARIMA(y, order=(1, 1, 1), trend='t')
    model_fit = model.fit()

    forecast_steps = 15
    forecast_obj = model_fit.get_forecast(steps=forecast_steps)
    forecast = forecast_obj.predicted_mean
    conf_int = forecast_obj.conf_int()
    future_years = np.arange(years[-1] + 1, years[-1] + 1 + forecast_steps)

    # NEW FIX: Stitch the historical line and forecast line together so there is no visual gap
    plot_years = np.insert(future_years, 0, years[-1])
    plot_forecast = np.insert(forecast, 0, y[-1])
    lower_bound = np.insert(conf_int[:, 0], 0, y[-1])
    upper_bound = np.insert(conf_int[:, 1], 0, y[-1])

    moving_avg = pd.Series(y).rolling(window=5).mean()

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=years, y=y, mode='lines', name='Historical Data', line=dict(color='#bdc3c7', width=1)))
    fig.add_trace(go.Scatter(x=years, y=moving_avg, mode='lines', name='5-Year Moving Average', line=dict(color='#2c3e50', width=2)))

    # Plot stitched forecast
    fig.add_trace(go.Scatter(x=plot_years, y=plot_forecast, mode='lines', name='ARIMA Forecast', line=dict(color='#e67e22', width=3, dash='dash')))

    # Plot stitched Confidence Interval
    fig.add_trace(go.Scatter(x=np.concatenate([plot_years, plot_years[::-1]]),
                             y=np.concatenate([lower_bound, upper_bound[::-1]]),
                             fill='toself', fillcolor='rgba(230, 126, 34, 0.2)', line=dict(color='rgba(255,255,255,0)'),
                             hoverinfo="skip", showlegend=True, name='95% Confidence Interval'))

    fig.update_layout(title=f'ARIMA Temperature Forecast & Trend ({season})', xaxis_title='Year', yaxis_title='Mean Temperature (°C)', template=layout_template, hovermode="x unified")
    return fig

# To Run APP
if __name__ == '__main__':
    from google.colab import output
    import logging

    log = logging.getLogger('werkzeug')
    log.setLevel(logging.ERROR)

    print("\n" + "="*60)
    print("LINK TO DASHBOARD:")
    print(output.eval_js("google.colab.kernel.proxyPort(8050)"))
    print("="*60 + "\n")

    app.run(port=8050, debug=False)
